### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by pavangarlapati97** [DivyamSharma04/Covid-19-ChestXray-Prediction#1]
Please share your prerequisites(python packages with versions) in order to mitigate some issues.

**Comment by pavangarlapati97** [comment]
While trying to run the app.py these errors are popping out
Traceback (most recent call last):
  File "app.py", line 22, in <module>
    model = load_model(MODEL_PATH)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\keras\engine\saving.py", line 458, in load_wrapper
    return load_function(*args, **kwargs)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\keras\engine\saving.py", line 550, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\keras\engine\saving.py", line 243, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\keras\engine\saving.py", line 593, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\keras\layers\__init__.py", line 165, in deserialize
    return deserialize_keras_object(config,
  File "C:\Users\Administrator\anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 144, in deserialize_keras_object
    return cls.from_config(
  File "C:\Users\Administrator\anaconda3\lib\site-packages\keras\engine\sequential.py", line 300, in from_config
    layer = layer_module.deserialize(conf,
  File "C:\Users\Administrator\anaconda3\lib\site-packages\keras\layers\__init__.py", line 165, in deserialize
    return deserialize_keras_object(config,
  File "C:\Users\Administrator\anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 149, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "C:\Users\Administrator\anaconda3\lib\site-packages\keras\engine\base_layer.py", line 1103, in from_config
    return cls(**config)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'ragged'
